### ISSUE TITLE
Exporting as GTiff fails

### ISSUE THREAD

**Issue by Sijoma** [Open-EO/openeo-wcps-driver#17]
I am trying to export the result of the following process graph as a GTiff. If i send "GTiff" as the output format the process fails immediately. If I send 'tiff', it fails after some time.

Process graph:

{
  "imagery": {
    "red": "B04",
    "nir": "B08",
    "imagery": {
      "extent": [
        "2018-06-04T00:00:00Z",
        "2018-06-04T23:59:59Z"
      ],
      "imagery": {
        "extent": {
          "west": 8.71,
          "south": 47,
          "east": 9.8,
          "north": 47.8
        },
        "imagery": {
          "process_id": "get_collection",
          "name": "openEO_S2_32632_10m_L2A"
        },
        "process_id": "filter_bbox"
      },
      "process_id": "filter_daterange"
    },
    "process_id": "NDVI"
  },
  "process_id": "min_time"
}

Error:

An error occured when retrieving preview query result from WCPS endpoint: Server returned HTTP response code: 500 for URL: http://saocompute.eurac.edu/rasdaman/ows?SERVICE=WCS&VERSION=2.0.1&REQUEST=ProcessCoverages&QUERY=for%20%24c1%20in%20%28%20openEO_S2_32632_10m_L2A%20%29%20return%20encode%20%28%20condense%20min%20over%20%24pm%20t%20%28imageCrsDomain%28%24c1%5BDATE%28%222018-06-04T00%3A00%3A00Z%22%3A%222018-06-04T23%3A59%3A59Z%22%29%5D%2CDATE%29%29%20using%20%28%28double%29%24c1.B08%5BE%28477952.58941835706%3A559906.504051826%29%2CN%285205204.916923406%3A5294381.277720123%29%2CDATE%28%24pm%29%5D%20-%20%24c1.B04%5BE%28477952.58941835706%3A559906.504051826%29%2CN%285205204.916923406%3A5294381.277720123%29%2CDATE%28%24pm%29%5D%29%20%2F%20%28%28double%29%24c1.B08%5BE%28477952.58941835706%3A559906.504051826%29%2CN%285205204.916923406%3A5294381.277720123%29%2CDATE%28%24pm%29%5D%20%2B%20%24c1.B04%5BE%28477952.58941835706%3A559906.504051826%29%2CN%285205204.916923406%3A5294381.277720123%29%2CDATE%28%24pm%29%5D%29%2C%20%22TIFF%22%20%29

**Comment by aljacob** [comment]
thanks for reporting this error. This issue has been resolved now.
