### ISSUE TITLE
Endpoint /job/:id/results does not return JSON

### ISSUE THREAD

**Issue by Sijoma** [Open-EO/openeo-wcps-driver#18]
Backend version: 0.3.1
Link: http://saocompute.eurac.edu/openEO_0_3_0/openeo/

The endpoint /job/:job_id/results does return the results directly (eg. an image), instead it should return a JSON with information such as a link to the resource, job_id, title, description, updated.

(see https://open-eo.github.io/openeo-api/apireference/#tag/Batch-Job-Management/paths/~1jobs~1{job_id}~1results/get)

**Comment by aljacob** [comment]
fixed in 0.4.2 version
