### ISSUE TITLE
Process parameters are missing required schema property

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-wcps-driver#4]
The openEO Hub can't display the processes because their parameters don't have a `schema` property. The API *requires* this property, and therefore the <Process> component I re-use from Matthias' processes-docgen tool expects it to be present, and fails to render if it isn't.

Could you add the `schema` property to your parameter objects? A quick workaround could be to always output an empty object:

````
"parameters": {
    "name": {
        "description": "Filter by collection name",
        "schema": {}
    }
}
````

**Comment by christophfriedrich** [comment]
Thanks! Almost all parameters now have the property :+1: 
Only `filter_daterange`'s `extent` parameter is still missing it, maybe you overlooked that one?

**Comment by aljacob** [comment]
I see the extent parameter here:
http://saocompute.eurac.edu/openEO_0_3_0/openeo/processes

**Comment by christophfriedrich** [comment]
Yes, the parameter is there, what I meant: the object that describes the `extent` parameter is missing the `schema` property (clarified above)

**Comment by prateekbudhwar** [comment]
@christophfriedrich @m-mohr I see that the schema property for filter_daterange process is missing in the API docs as well, maybe thatswhy we skipped it too in our backend processes too. I will put the schema property in filter_daterange process once you confirm the correct format to be used for it. What I can guess so far is that the items property in the extent is mistakenly put for schema, and also do we need the type property too in the extent, I dont see it in any other processes. Can you you check it too please ? Thanks

**Comment by m-mohr** [comment]
@prateekbudhwar I don't quite understand your point. Where is the schema missing in filter_daterange? If I look at the official release ( https://github.com/Open-EO/openeo-api/blob/master/processes.json ), I can see schemas for both parameters and the return value. The correct format for the schema property  as defined in the API specification is valid JSON schema.

**Comment by aljacob** [comment]
@m-mohr we were confused because in the API documentation here in the examples it is missing: https://open-eo.github.io/openeo-api/v/0.3.1/apireference/#tag/Process-Discovery , thanks for pointing us the official spec then!

**Comment by m-mohr** [comment]
Oh, I see, that's my fault. And I intentionally obfuscated the examples to avoid copying them over as these are only (obiously also a bit faulty) examples and not the actual processes we use. ;-) Anyway, will be fixed in the next API release.

**Comment by prateekbudhwar** [comment]
@m-mohr Also one more query, the type field is an array in the process filter_daterange and as object in rest other processes. Is it also correct ? Let us know, thanks

**Comment by m-mohr** [comment]
That is correct.

**Comment by aljacob** [comment]
those issues should now all be fixed
