### ISSUE TITLE
OIDC access_token should be used as bearer token

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-wcps-driver#45]
I'm just creating this issue for linking and tracking purposes.

EURAC backend apparently expects bearer token to be the id_token, however the access_token should be used.

also see:
- https://github.com/Open-EO/openeo-api/issues/219
- https://openeo.org/documentation/1.0/developers/api/reference.html#operation/authenticate-oidc

**Comment by soxofaan** [comment]
Is this already resolved?

we have a temp workaround for this in the python client and I'm wondering if we can drop it:
https://github.com/Open-EO/openeo-python-client/blob/a9d2d67333762ff1e715efe511fe31f9a5112448/openeo/rest/connection.py#L207-L210

**Comment by soxofaan** [comment]
according to @clausmichele  in https://github.com/Open-EO/openeo-python-client/issues/300#issuecomment-1246836250  this can be closed if I understand correctly

**Comment by clausmichele** [comment]
Yes thanks. By the way, I think we don't use this repo anymore right @aljacob ? The one to refer to for the Eurac back-end is https://github.com/Open-EO/openeo-spring-driver
