### ISSUE TITLE
Support for HTTPS

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-wcps-driver#5]
The API requires HTTPS (instead of HTTP) for the API as authentication credentials with HTTP Basic, OAuth2 and OpenID Connect are transmitted without encryption to the server so they can "easily" be sniffed by a third-person. Therefore the WCPS driver should support HTTPS and the deployed instance should activate it by default.

Another issue is, that the Web Editor, which is deployed with HTTPS can't connect to HTTP back-ends due to browsers forbidding "mixed content" (i.e. forbidding insecure HTTP connections being established by secure/HTTPS web pages). Providing the Web Editor with HTTP would promote insecure workflows and therefore is not desirable.

**Comment by aljacob** [comment]
@m-mohr we are looking into it!
@arcostarusty could please help with the setup?

**Comment by arcostarusty** [comment]
@aljacob Ok, I'll setup the HTTPS authentication for the application server and that runs the WCPS driver

**Comment by aljacob** [comment]
https is now available
