### ISSUE TITLE
metadata for ADO_CORINE_100m_3035

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-wcps-driver#51]
Hey,

I just had a quick look at your ADO_CORINE_100m_3035 collection while working on a web editor issue.

Some hints for improvements.
- The metadata should not do those "No <...> Information Available" summaries. Instead, just remove them from the output.
- The role "Producer" should be lower-cased.
- If you provide an e-mail in a "url" field, add "mailto:" at the beginning.
- eo:gsd doesn't exist anymore, it's now just "gsd"
- citation doesn't exist, I think you meant to use "sci:citation"? In this case also add "scientific" to "stac_extensions".

**Comment by aljacob** [comment]
can you re-open under the spring driver?
