### ISSUE TITLE
v0.3.1: Job creation end point

### ISSUE THREAD

**Issue by bgoesswe** [Open-EO/openeo-wcps-driver#6]
Creating a Job using the POST [/Jobs end point](https://open-eo.github.io/openeo-api/v/0.3.1/apireference/#tag/Job-Management/paths/~1jobs/post)

The response on success differ from the API: 

- Response code should be 201 and not 200
- The job_id should be in the header of the response as "location" and "openeo-identifier" (see [here](https://open-eo.github.io/openeo-api/v/0.3.1/apireference/#tag/Job-Management/paths/~1jobs/post))

**Comment by aljacob** [comment]
response code should be fixed now.
Header still needs to be updated

**Comment by aljacob** [comment]
fixed in 0.4.2 version
