### ISSUE TITLE
v0.3.1: Endpoint for starting Job and receiving Job results is not available

### ISSUE THREAD

**Issue by bgoesswe** [Open-EO/openeo-wcps-driver#7]
The endpoint for starting a job (POST /jobs/<job_id>/results) does not exist.
Same for the endpoint of retrieving job results (GET /jobs/<job_id>/results).

Response from Apache Tomcat: 
HTTP Status 404 - Not Found

**Comment by aljacob** [comment]
GET /jobs/<job_id>/results does now exist.
currently job execution will be triggered lazily when GET is called. so no POST for result as of now

**Comment by bgoesswe** [comment]
Ok thanks perfect, it works

**Comment by bgoesswe** [comment]
Still you may need to add the POST endpoint to be compatible with the work-flow of the other back ends (even if its just a mock up). 
For synchronous job execution the  [POST /preview ](https://open-eo.github.io/openeo-api/v/0.3.1/apireference/#tag/Job-Management/paths/~1preview/post)endpoint would be more suitable.

**Comment by aljacob** [comment]
ok synchronous execution is now available via POST /preview.
I will still have to update for the triggering of jobs in batch mode though via POST /results

**Comment by aljacob** [comment]
fixed in 0.4.2 branch
